velos:
    path:     /
    defaults: { _controller: EcommerceBundle:Velos:velos }


presentation:
    path:     /velo/{id}
    defaults: { _controller: EcommerceBundle:Velos:presentation }

panier:
    path:     /panier
    defaults: { _controller: EcommerceBundle:Panier:panier }


livraison:
    path:     /panier/livraison
    defaults: { _controller: EcommerceBundle:Panier:livraison }

validation:
    path:     /panier/validation
    defaults: { _controller: EcommerceBundle:Panier:validation }

categorieVelos:
    path:     /categorie/{categorie}
    defaults: { _controller: EcommerceBundle:Velos:categorie }

rechercheVelos:
    path:     /recherche
    defaults: { _controller: EcommerceBundle:Velos:rechercheTraitement }



